aws:
  region: "us-east-2"
  s3_bucket: "mutual-fund-tracker-demo"
  bedrock_model_id: "your_bedrock_model_id" #Please use the model ID for model selected in the Bedrock 

file_paths:
  input_data: "../datasets/input_data.csv"
  output_results: "../datasets/output_results.csv"
